apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: your-dockerhub-username/ecommerce-senior-backend-assessment:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "mysql://user:root@mysql:3306/user_db"
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq:5672"
        - name: REDIS_URL
          value: "redis://redis:6379"
