global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'ecommerce-senior-backend-assessment'
    static_configs:
      - targets: ['localhost:3005']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
